AllCops:
    NewCops: enable
    SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'spec/*.rb'

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Layout/DotPosition:
  EnforcedStyle: trailing

Layout/LineLength:
  Exclude:
    - 'spec/**/*.rb'
    - 'spec/*.rb'
